### ISSUE TITLE
Punctuation patch

### ISSUE THREAD

**Issue by alexeyten** [shytikov/pragmasevka#2]
I see that you build semibold/black variants just to take punctuations from them.

Have you tried to change [`periodSize`](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md#metric-override)?

E.g.
```toml
[buildPlans.pragmasevka.metric-override]
periodSize = 'default_periodSize * 1.2'
```
